In [1]:
import tensorflow
import tensorflow.keras as keras
from keras.models import Sequential, load_model
from keras.layers import Reshape, Permute, GRU
from keras.layers import Dense, Activation, Conv2D, MaxPool2D, BatchNormalization, Flatten, Dropout, LSTM
from keras.callbacks import ModelCheckpoint, TensorBoard, ReduceLROnPlateau
import matplotlib.pyplot as plt
import pandas as pd
import zipfile
import numpy as np

In [2]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 5.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 984.4 kB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 20.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 36.3 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.5/304.5 kB 4.7 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 22.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 3.3 MB/s eta 0:00:000:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 2.6 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 35.4 MB/s eta 0:00:00:

In [10]:
# load test data
X_test = np.load('mfcc30s20_arrays/X_test.npy')
y_test = np.load('mfcc30s20_arrays/y_test.npy')

In [5]:
zip_file_path = 'cnn1.zip'
extract_path = 'cnn1'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [3]:
cnn1 = tensorflow.keras.models.load_model('cnn1')

In [5]:
cnn1.compile(optimizer=keras.optimizers.Adam(learning_rate= 0.001),
             loss = keras.losses.binary_crossentropy,
             metrics = [keras.metrics.AUC(name="auc"),
                        keras.metrics.Precision(name="precision"),
                        keras.metrics.Recall(name="recall")])

In [6]:
cnn1.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_8 (Conv2D)           (None, 1290, 18, 32)      320       
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 645, 9, 32)       0         
 2D)                                                             
                                                                 
 batch_normalization_8 (Batc  (None, 645, 9, 32)       128       
 hNormalization)                                                 
                                                                 
 dropout_10 (Dropout)        (None, 645, 9, 32)        0         
                                                                 
 conv2d_9 (Conv2D)           (None, 643, 7, 64)        18496     
                                                                 
 max_pooling2d_9 (MaxPooling  (None, 215, 4, 64)      

In [13]:
# evaluate the CNN on the test set - examplary output for non-augmented 3 second segments with 20 MFCC coefficients
# Assuming you have X_test and y_test as your test data

# Evaluate the model on the test set
loss, auc, precision, recall = cnn1.evaluate(X_test, y_test)

# Print the test accuracy and other metrics
# print(f'Test Accuracy: {accuracy}')
print(f'AUC: {auc}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')


45/45 [==============================] - 1s 22ms/step - loss: 0.7129 - auc: 0.4897 - precision: 0.1261 - recall: 0.5222
AUC: 0.48969870805740356
Precision: 0.12608341872692108
Recall: 0.5221536755561829


In [14]:
zip_file_path = 'cnn2.zip'
extract_path = 'cnn2'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [15]:
cnn2 = tensorflow.keras.models.load_model('cnn2')

In [16]:
cnn2.compile(optimizer=keras.optimizers.Adam(learning_rate= 0.001),
             loss = keras.losses.binary_crossentropy,
             metrics = [keras.metrics.AUC(name="auc"),
                        keras.metrics.Precision(name="precision"),
                        keras.metrics.Recall(name="recall")])

In [17]:
cnn2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_10 (Conv2D)          (None, 1292, 20, 32)      320       
                                                                 
 max_pooling2d_10 (MaxPoolin  (None, 646, 19, 32)      0         
 g2D)                                                            
                                                                 
 batch_normalization_10 (Bat  (None, 646, 19, 32)      128       
 chNormalization)                                                
                                                                 
 dropout_13 (Dropout)        (None, 646, 19, 32)       0         
                                                                 
 conv2d_11 (Conv2D)          (None, 644, 17, 64)       18496     
                                                                 
 max_pooling2d_11 (MaxPoolin  (None, 322, 16, 64)     

In [18]:
# evaluate the CNN on the test set - examplary output for non-augmented 3 second segments with 20 MFCC coefficients
# Assuming you have X_test and y_test as your test data

# Evaluate the model on the test set
loss, auc, precision, recall = cnn2.evaluate(X_test, y_test)

# Print the test accuracy and other metrics
# print(f'Test Accuracy: {accuracy}')
print(f'AUC: {auc}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')


45/45 [==============================] - 7s 146ms/step - loss: 0.4453 - auc: 0.6148 - precision: 0.2384 - recall: 0.0550
AUC: 0.6147589683532715
Precision: 0.2384428232908249
Recall: 0.05496354401111603


In [19]:
zip_file_path = 'cnn3.zip'
extract_path = 'cnn3'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [20]:
cnn3 = tensorflow.keras.models.load_model('cnn3')

In [21]:
cnn3.compile(optimizer=keras.optimizers.Adam(learning_rate= 0.001),
             loss = keras.losses.binary_crossentropy,
             metrics = [keras.metrics.AUC(name="auc"),
                        keras.metrics.Precision(name="precision"),
                        keras.metrics.Recall(name="recall")])

In [22]:
cnn3.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 646, 20, 128)      1280      
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 323, 10, 128)     0         
 2D)                                                             
                                                                 
 batch_normalization_5 (Batc  (None, 323, 10, 128)     512       
 hNormalization)                                                 
                                                                 
 dropout_4 (Dropout)         (None, 323, 10, 128)      0         
                                                                 
 conv2d_5 (Conv2D)           (None, 161, 8, 384)       442752    
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 81, 4, 384)      

In [23]:
# evaluate the CNN on the test set - examplary output for non-augmented 3 second segments with 20 MFCC coefficients
# Assuming you have X_test and y_test as your test data

# Evaluate the model on the test set
loss, auc, precision, recall = cnn3.evaluate(X_test, y_test)

# Print the test accuracy and other metrics
# print(f'Test Accuracy: {accuracy}')
print(f'AUC: {auc}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')


45/45 [==============================] - 4s 78ms/step - loss: 0.4717 - auc: 0.7034 - precision: 0.3022 - recall: 0.2036
AUC: 0.7033874988555908
Precision: 0.30224812030792236
Recall: 0.20358945429325104


In [24]:
predictions = cnn3.predict(X_test)

45/45 [==============================] - 4s 79ms/step


In [25]:
predictions.shape

(1413, 10)

In [41]:
# multi label predictions and accuracy measures
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, multilabel_confusion_matrix, classification_report

In [30]:
!pip install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 29.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 4.2 MB/s eta 0:00:0000:01


In [ ]:
def multi_label_scores(model):
    
    thresholds = [0.5] * 10
    predictions = model.predict(X_test)
    y_pred_labels = np.where(predictions >= thresholds, 1, 0)
    
    report = classification_report(
            y_test,
            y_pred_labels,
            output_dict=False,
            target_names=['inspiring', 'energetic', 'happy', 'sad', 'motivational', 'relaxing', 'uplifting', 'calm', 'love','hopeful'],
            zero_division=1
            )
    print(report)
    

In [32]:
# how to choose the thresholds?
thresholds = [0.5] * 10
print(thresholds)

[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]


In [33]:
y_pred_labels = np.where(predictions >= thresholds, 1, 0)

In [35]:
accuracy = accuracy_score(y_test, y_pred_labels)
precision = precision_score(y_test, y_pred_labels, average='micro')
recall = recall_score(y_test, y_pred_labels, average='micro')
f1 = f1_score(y_test, y_pred_labels, average='micro')

In [36]:
print(f"Accuracy: {accuracy:.4f}")
print("The accuracy score represents the overall accuracy of the predictions, which is the ratio of correct predictions to the total number of samples.")

print(f"Precision: {precision:.4f}")
print("Precision measures the proportion of correctly predicted positive labels (true positives) out of all positive predictions. A higher precision indicates a lower false positive rate.")

print(f"Recall: {recall:.4f}")
print("Recall, also known as sensitivity or true positive rate, measures the proportion of correctly predicted positive labels (true positives) out of all actual positive samples. A higher recall indicates a lower false negative rate.")

print(f"F1 Score: {f1:.4f}")
print("The F1 score is the harmonic mean of precision and recall. It provides a balanced measure of the model's performance by considering both precision and recall. It is a single metric that summarizes the model's accuracy and completeness.")

Accuracy: 0.1047
The accuracy score represents the overall accuracy of the predictions, which is the ratio of correct predictions to the total number of samples.
Precision: 0.3022
Precision measures the proportion of correctly predicted positive labels (true positives) out of all positive predictions. A higher precision indicates a lower false positive rate.
Recall: 0.2036
Recall, also known as sensitivity or true positive rate, measures the proportion of correctly predicted positive labels (true positives) out of all actual positive samples. A higher recall indicates a lower false negative rate.
F1 Score: 0.2433
The F1 score is the harmonic mean of precision and recall. It provides a balanced measure of the model's performance by considering both precision and recall. It is a single metric that summarizes the model's accuracy and completeness.


In [39]:
# multi label confusion matrix
confusion_matrix = multilabel_confusion_matrix(y_test, y_pred_labels)

for i, matrix in enumerate(confusion_matrix):
    print(f"Confusion matrix for label {i+1}:")
    print(matrix)
    print()

Confusion matrix for label 1:
[[1305   12]
 [  95    1]]

Confusion matrix for label 2:
[[1136   18]
 [ 239   20]]

Confusion matrix for label 3:
[[946 133]
 [243  91]]

Confusion matrix for label 4:
[[1356   17]
 [  39    1]]

Confusion matrix for label 5:
[[1006  228]
 [ 120   59]]

Confusion matrix for label 6:
[[1194   26]
 [ 172   21]]

Confusion matrix for label 7:
[[1198   83]
 [ 111   21]]

Confusion matrix for label 8:
[[868 277]
 [128 140]]

Confusion matrix for label 9:
[[1239   24]
 [ 145    5]]

Confusion matrix for label 10:
[[1261   20]
 [ 128    4]]



In [43]:
# averages of a metrics — precision, recall or f1-score — over all classes
report = classification_report(
            y_test,
            y_pred_labels,
            output_dict=False,
            target_names=['inspiring', 'energetic', 'happy', 'sad', 'motivational', 'relaxing', 'uplifting', 'calm', 'love','hopeful'],
            zero_division=1
            )

print(report)

              precision    recall  f1-score   support

   inspiring       0.08      0.01      0.02        96
   energetic       0.53      0.08      0.13       259
       happy       0.41      0.27      0.33       334
         sad       0.06      0.03      0.03        40
motivational       0.21      0.33      0.25       179
    relaxing       0.45      0.11      0.17       193
   uplifting       0.20      0.16      0.18       132
        calm       0.34      0.52      0.41       268
        love       0.17      0.03      0.06       150
     hopeful       0.17      0.03      0.05       132

   micro avg       0.30      0.20      0.24      1783
   macro avg       0.26      0.16      0.16      1783
weighted avg       0.32      0.20      0.21      1783
 samples avg       0.56      0.19      0.18      1783

