In [4]:
import tensorflow
import tensorflow.keras as keras
from keras.models import Sequential, load_model
from keras.layers import Reshape, Permute, GRU
from keras.layers import Dense, Activation, Conv2D, MaxPool2D, BatchNormalization, Flatten, Dropout, LSTM
from keras.callbacks import ModelCheckpoint, TensorBoard, ReduceLROnPlateau
import matplotlib.pyplot as plt
import pandas as pd
# import zipfile
import numpy as np

In [30]:
# multi label predictions and accuracy measures
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, multilabel_confusion_matrix, classification_report, roc_auc_score, average_precision_score

In [3]:
!pip install scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 21.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 2.6 MB/s eta 0:00:0000:01


In [1]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 6.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 1.2 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 25.1 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 11.3 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 12.2 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 9.0 MB/s eta 0:00:000:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 1.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.5/304.5 kB 7.4 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 772.5 kB/s eta 0:00:00a 0:00:

In [6]:
# load test data
X_test = np.load('mfcc30s20_arrays/X_test.npy')
y_test = np.load('mfcc30s20_arrays/y_test.npy')

In [5]:
zip_file_path = 'cnn1.zip'
extract_path = 'cnn1'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [7]:
cnn1 = tensorflow.keras.models.load_model('cnn1')

In [8]:
cnn1.compile(optimizer=keras.optimizers.Adam(learning_rate= 0.001),
             loss = keras.losses.binary_crossentropy,
             metrics = [keras.metrics.AUC(name="auc"),
                        keras.metrics.Precision(name="precision"),
                        keras.metrics.Recall(name="recall")])

In [9]:
cnn1.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_8 (Conv2D)           (None, 1290, 18, 32)      320       
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 645, 9, 32)       0         
 2D)                                                             
                                                                 
 batch_normalization_8 (Batc  (None, 645, 9, 32)       128       
 hNormalization)                                                 
                                                                 
 dropout_10 (Dropout)        (None, 645, 9, 32)        0         
                                                                 
 conv2d_9 (Conv2D)           (None, 643, 7, 64)        18496     
                                                                 
 max_pooling2d_9 (MaxPooling  (None, 215, 4, 64)      

In [13]:
# evaluate the CNN on the test set - examplary output for non-augmented 3 second segments with 20 MFCC coefficients
# Assuming you have X_test and y_test as your test data

# Evaluate the model on the test set
loss, auc, precision, recall = cnn1.evaluate(X_test, y_test)

# Print the test accuracy and other metrics
# print(f'Test Accuracy: {accuracy}')
print(f'AUC: {auc}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')


45/45 [==============================] - 1s 22ms/step - loss: 0.7129 - auc: 0.4897 - precision: 0.1261 - recall: 0.5222
AUC: 0.48969870805740356
Precision: 0.12608341872692108
Recall: 0.5221536755561829


In [14]:
zip_file_path = 'cnn2.zip'
extract_path = 'cnn2'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [10]:
cnn2 = tensorflow.keras.models.load_model('cnn2')

In [11]:
cnn2.compile(optimizer=keras.optimizers.Adam(learning_rate= 0.001),
             loss = keras.losses.binary_crossentropy,
             metrics = [keras.metrics.AUC(name="auc"),
                        keras.metrics.Precision(name="precision"),
                        keras.metrics.Recall(name="recall")])

In [12]:
cnn2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_10 (Conv2D)          (None, 1292, 20, 32)      320       
                                                                 
 max_pooling2d_10 (MaxPoolin  (None, 646, 19, 32)      0         
 g2D)                                                            
                                                                 
 batch_normalization_10 (Bat  (None, 646, 19, 32)      128       
 chNormalization)                                                
                                                                 
 dropout_13 (Dropout)        (None, 646, 19, 32)       0         
                                                                 
 conv2d_11 (Conv2D)          (None, 644, 17, 64)       18496     
                                                                 
 max_pooling2d_11 (MaxPoolin  (None, 322, 16, 64)     

In [18]:
# evaluate the CNN on the test set - examplary output for non-augmented 3 second segments with 20 MFCC coefficients
# Assuming you have X_test and y_test as your test data

# Evaluate the model on the test set
loss, auc, precision, recall = cnn2.evaluate(X_test, y_test)

# Print the test accuracy and other metrics
# print(f'Test Accuracy: {accuracy}')
print(f'AUC: {auc}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')


45/45 [==============================] - 7s 146ms/step - loss: 0.4453 - auc: 0.6148 - precision: 0.2384 - recall: 0.0550
AUC: 0.6147589683532715
Precision: 0.2384428232908249
Recall: 0.05496354401111603


In [19]:
zip_file_path = 'cnn3.zip'
extract_path = 'cnn3'

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

In [13]:
cnn3 = tensorflow.keras.models.load_model('cnn3')

In [14]:
cnn3.compile(optimizer=keras.optimizers.Adam(learning_rate= 0.001),
             loss = keras.losses.binary_crossentropy,
             metrics = [keras.metrics.AUC(name="auc"),
                        keras.metrics.Precision(name="precision"),
                        keras.metrics.Recall(name="recall")])

In [15]:
cnn3.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 646, 20, 128)      1280      
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 323, 10, 128)     0         
 2D)                                                             
                                                                 
 batch_normalization_5 (Batc  (None, 323, 10, 128)     512       
 hNormalization)                                                 
                                                                 
 dropout_4 (Dropout)         (None, 323, 10, 128)      0         
                                                                 
 conv2d_5 (Conv2D)           (None, 161, 8, 384)       442752    
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 81, 4, 384)      

In [23]:
# evaluate the CNN on the test set - examplary output for non-augmented 3 second segments with 20 MFCC coefficients
# Assuming you have X_test and y_test as your test data

# Evaluate the model on the test set
loss, auc, precision, recall = cnn3.evaluate(X_test, y_test)

# Print the test accuracy and other metrics
# print(f'Test Accuracy: {accuracy}')
print(f'AUC: {auc}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')


45/45 [==============================] - 4s 78ms/step - loss: 0.4717 - auc: 0.7034 - precision: 0.3022 - recall: 0.2036
AUC: 0.7033874988555908
Precision: 0.30224812030792236
Recall: 0.20358945429325104


In [24]:
predictions = cnn3.predict(X_test)

45/45 [==============================] - 4s 79ms/step


In [25]:
predictions.shape

(1413, 10)

In [32]:
# how to choose the thresholds?
thresholds = [0.5] * 10
print(thresholds)

[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]


In [33]:
y_pred_labels = np.where(predictions >= thresholds, 1, 0)

In [35]:
accuracy = accuracy_score(y_test, y_pred_labels)
precision = precision_score(y_test, y_pred_labels, average='micro')
recall = recall_score(y_test, y_pred_labels, average='micro')
f1 = f1_score(y_test, y_pred_labels, average='micro')

In [36]:
print(f"Accuracy: {accuracy:.4f}")
print("The accuracy score represents the overall accuracy of the predictions, which is the ratio of correct predictions to the total number of samples.")

print(f"Precision: {precision:.4f}")
print("Precision measures the proportion of correctly predicted positive labels (true positives) out of all positive predictions. A higher precision indicates a lower false positive rate.")

print(f"Recall: {recall:.4f}")
print("Recall, also known as sensitivity or true positive rate, measures the proportion of correctly predicted positive labels (true positives) out of all actual positive samples. A higher recall indicates a lower false negative rate.")

print(f"F1 Score: {f1:.4f}")
print("The F1 score is the harmonic mean of precision and recall. It provides a balanced measure of the model's performance by considering both precision and recall. It is a single metric that summarizes the model's accuracy and completeness.")

Accuracy: 0.1047
The accuracy score represents the overall accuracy of the predictions, which is the ratio of correct predictions to the total number of samples.
Precision: 0.3022
Precision measures the proportion of correctly predicted positive labels (true positives) out of all positive predictions. A higher precision indicates a lower false positive rate.
Recall: 0.2036
Recall, also known as sensitivity or true positive rate, measures the proportion of correctly predicted positive labels (true positives) out of all actual positive samples. A higher recall indicates a lower false negative rate.
F1 Score: 0.2433
The F1 score is the harmonic mean of precision and recall. It provides a balanced measure of the model's performance by considering both precision and recall. It is a single metric that summarizes the model's accuracy and completeness.


In [48]:
# predict labels of test set with optimized thresholds
y_pred_val = cnn3.predict(X_val)
thresholds = optimize_thresholds(y_val, y_pred_val)
y_pred_test = cnn3.predict(X_test)


45/45 [==============================] - 32s 707ms/step


In [50]:
y_pred_labels = np.where(y_pred_test >= thresholds, 1, 0)

In [53]:
# multi label confusion matrix and accuracy
confusion_matrix = multilabel_confusion_matrix(y_test, y_pred_labels)

true = 0
false = 0

for i, matrix in enumerate(confusion_matrix):
    print(f"Confusion matrix for label {i+1}:")
    print(matrix)
    print()
    
    true += matrix[0,0] + matrix[1,1]
    false += matrix[0,1] + matrix[1,0]

print("Accuracy:", true / (true+false))


Confusion matrix for label 1:
[[1232   85]
 [  82   14]]

Confusion matrix for label 2:
[[892 262]
 [104 155]]

Confusion matrix for label 3:
[[590 489]
 [ 98 236]]

Confusion matrix for label 4:
[[1313   60]
 [  37    3]]

Confusion matrix for label 5:
[[819 415]
 [ 95  84]]

Confusion matrix for label 6:
[[946 274]
 [ 82 111]]

Confusion matrix for label 7:
[[1055  226]
 [  73   59]]

Confusion matrix for label 8:
[[749 396]
 [ 94 174]]

Confusion matrix for label 9:
[[1121  142]
 [ 103   47]]

Confusion matrix for label 10:
[[803 478]
 [ 52  80]]

Accuracy: 0.7418966737438075


In [43]:
# averages of a metrics — precision, recall or f1-score — over all classes
report = classification_report(
            y_test,
            y_pred_labels,
            output_dict=False,
            target_names=['inspiring', 'energetic', 'happy', 'sad', 'motivational', 'relaxing', 'uplifting', 'calm', 'love','hopeful'],
            zero_division=1
            )

print(report)

              precision    recall  f1-score   support

   inspiring       0.08      0.01      0.02        96
   energetic       0.53      0.08      0.13       259
       happy       0.41      0.27      0.33       334
         sad       0.06      0.03      0.03        40
motivational       0.21      0.33      0.25       179
    relaxing       0.45      0.11      0.17       193
   uplifting       0.20      0.16      0.18       132
        calm       0.34      0.52      0.41       268
        love       0.17      0.03      0.06       150
     hopeful       0.17      0.03      0.05       132

   micro avg       0.30      0.20      0.24      1783
   macro avg       0.26      0.16      0.16      1783
weighted avg       0.32      0.20      0.21      1783
 samples avg       0.56      0.19      0.18      1783



In [24]:
y_val = np.load('mfcc30s20_arrays/y_val.npy')
X_val = np.load('mfcc30s20_arrays/X_val.npy')

In [44]:
# optimize thresholds on the validation set maximizing macro f1 score
def optimize_thresholds(y_val, y_pred_val):
    thresholds = []
    
    for i in range(y_val.shape[1]):
        best_threshold = 0
        best_f1 = 0
        
        # Vary threshold from 0 to 1 with a small step size
        for threshold in np.arange(0.1, 1.0, 0.05):
            y_pred_thresholded = (y_pred_val[:, i] >= threshold).astype(int)
            f1 = f1_score(y_val[:, i], y_pred_thresholded)
            
            # Update best threshold if F1-score is higher
            if f1 > best_f1:
                best_f1 = f1
                best_threshold = threshold
        
        thresholds.append(best_threshold)
    
    return thresholds

In [54]:
def multi_label_scores(model):
    
    y_pred_val = model.predict(X_val)
    
    thresholds = optimize_thresholds(y_val, y_pred_val)
    
    y_pred_test = model.predict(X_test)
    
    y_pred_labels = np.where(y_pred_test >= thresholds, 1, 0)
    
    # precision, recall, f1
    report = classification_report(
            y_test,
            y_pred_labels,
            output_dict=False,
            target_names=['inspiring', 'energetic', 'happy', 'sad', 'motivational', 'relaxing', 'uplifting', 'calm', 'love','hopeful'],
            )
    
    # calculate multi label accuracy using confusion matrix
    confusion_matrix = multilabel_confusion_matrix(y_test, y_pred_labels)
    
    true = 0
    false = 0

    for i, matrix in enumerate(confusion_matrix):
        # print(f"Confusion matrix for label {i+1}:")
        # print(matrix)
        # print()

        true += matrix[0,0] + matrix[1,1]
        false += matrix[0,1] + matrix[1,0]

    print(report)
    print()
    print("Multi-label accuracy:", true / (true+false))
    

In [55]:
multi_label_scores(cnn1)

45/45 [==============================] - 10s 221ms/step
              precision    recall  f1-score   support

   inspiring       0.07      1.00      0.13        96
   energetic       0.18      1.00      0.31       259
       happy       0.24      1.00      0.38       334
         sad       0.03      1.00      0.06        40
motivational       0.13      1.00      0.22       179
    relaxing       0.14      1.00      0.24       193
   uplifting       0.09      1.00      0.17       132
        calm       0.19      1.00      0.32       268
        love       0.11      1.00      0.19       150
     hopeful       0.09      1.00      0.17       132

   micro avg       0.13      1.00      0.22      1783
   macro avg       0.13      1.00      0.22      1783
weighted avg       0.15      1.00      0.26      1783
 samples avg       0.13      1.00      0.22      1783


Multi-label accuracy: 0.12618542108987968


In [56]:
multi_label_scores(cnn2)

45/45 [==============================] - 69s 2s/step
              precision    recall  f1-score   support

   inspiring       0.11      0.34      0.17        96
   energetic       0.37      0.29      0.32       259
       happy       0.29      0.57      0.38       334
         sad       0.01      0.03      0.01        40
motivational       0.14      0.39      0.21       179
    relaxing       0.26      0.28      0.27       193
   uplifting       0.12      0.69      0.20       132
        calm       0.26      0.65      0.37       268
        love       0.15      0.26      0.19       150
     hopeful       0.13      0.14      0.14       132

   micro avg       0.20      0.42      0.27      1783
   macro avg       0.18      0.36      0.23      1783
weighted avg       0.23      0.42      0.27      1783
 samples avg       0.20      0.42      0.25      1783


Multi-label accuracy: 0.7101910828025477


/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [57]:
multi_label_scores(cnn3)

45/45 [==============================] - 32s 711ms/step
              precision    recall  f1-score   support

   inspiring       0.14      0.15      0.14        96
   energetic       0.37      0.60      0.46       259
       happy       0.33      0.71      0.45       334
         sad       0.05      0.07      0.06        40
motivational       0.17      0.47      0.25       179
    relaxing       0.29      0.58      0.38       193
   uplifting       0.21      0.45      0.28       132
        calm       0.31      0.65      0.42       268
        love       0.25      0.31      0.28       150
     hopeful       0.14      0.61      0.23       132

   micro avg       0.25      0.54      0.35      1783
   macro avg       0.22      0.46      0.29      1783
weighted avg       0.26      0.54      0.35      1783
 samples avg       0.26      0.54      0.33      1783


Multi-label accuracy: 0.7418966737438075


/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
# calculate thresholds optimized on val set (maximizing f1 score)
y_pred_val = model.predict(X_val) 
thresholds = optimize_thresholds(y_val, y_pred_val)

NameError: name 'model' is not defined

In [35]:
# calculate Macro ROC-AUC and PR-AUC

def macro_auc(model):
    
    y_pred_proba = model.predict(X_test)

    roc_auc_scores = []
    for i in range(10):
        roc_auc_scores.append(roc_auc_score(y_test[:, i], y_pred_proba[:, i]))

    # Calculate PR-AUC for each class
    pr_auc_scores = []
    for i in range(10):
        pr_auc_scores.append(average_precision_score(y_test[:, i], y_pred_proba[:, i]))

    # Calculate macro ROC-AUC and macro PR-AUC
    macro_roc_auc = np.mean(roc_auc_scores)
    macro_pr_auc = np.mean(pr_auc_scores)

    print("Macro ROC-AUC:", macro_roc_auc)
    print("Macro PR-AUC:", macro_pr_auc)

In [36]:
macro_auc(cnn1)

45/45 [==============================] - 10s 221ms/step
Macro ROC-AUC: 0.5046220968369951
Macro PR-AUC: 0.13175013649990233


In [37]:
macro_auc(cnn2)

45/45 [==============================] - 69s 2s/step
Macro ROC-AUC: 0.5865059431575961
Macro PR-AUC: 0.18280078191772292


In [38]:
macro_auc(cnn3)

45/45 [==============================] - 32s 709ms/step
Macro ROC-AUC: 0.6712056547274388
Macro PR-AUC: 0.22629314012176122
